name: Nosetests lvl2

on: [pull_request]

jobs:
  nose_tests_lvl2:
    runs-on: [self-hosted]

    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v2
      with:
        path: main_class
    - name: Checkout reference 🛎
      uses: actions/checkout@v2
      with:
        ref: devel
        path: ref_class
    - name: Create or update virtual Python environment
      run: |
        rm -f venv/bin/python
        virtualenv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install numpy scipy pandas matplotlib cython nose parameterized
    - name: make classy
      run: source venv/bin/activate && cd main_class && make -j
    - name: make reference classy
      run: |
        source venv/bin/activate
        cd ref_class
        sed -i.bak "s/'classy'/'classyref'/g" python/setup.py
        sed -i.bak 's/"classy"/"classyref"/g' python/setup.py
        make -j
    - name: Testing 🤖
      run: |
        source venv/bin/activate
        cd main_class/python
        OMP_NUM_THREADS=16 COMPARE_OUTPUT_REF=1 TEST_LEVEL=2 nosetests -v -a test_scenario test_class.py --nologcapture --nocapture
    - name: Upload plots 📤
      if: success() || failure()
      uses: actions/upload-artifact@v2
      with:
          name: BranchVsMasterPlots
          path: main_class/python/faulty_figs
